# Application Name
spring.application.name=joblisting

# MongoDB Atlas Connection URI
spring.data.mongodb.uri=mongodb+srv://root:tiger@cluster1.wugih6l.mongodb.net/Job?retryWrites=true&w=majority

# MongoDB Database Name
spring.data.mongodb.database=Job

# Server Port (Optional)
server.port=8080

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb=DEBUG

